[package]
name = "lsp4spl"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.3.0"
futures = "0.3.25"
httparse = "1.8.0"
lsp-types = "0.93.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
