[package]
name = "spl_frontend"
description = "Compiler-Frontend for SPL"
authors = ["AlecGhost"]
license = "MIT"
repository = "https://github.com/AlecGhost/LSP4SPL"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
nom_locate = "4.1.0"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
spl_frontend_macros = { version = "0.1.0", path  = "./spl_frontend_macros" }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
insta = "1.29.0"
pretty_assertions = "1.3.0"

[[bench]]
name = "benches"
harness = false
