[package]
name = "spl_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.2"
nom_locate = "4.0.0"
thiserror = "1.0.38"
tokio = { version = "1.24.1", features = ["full"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
