[package]
name = "spl_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
nom_locate = "4.1.0"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
spl_frontend_macros = { path  = "./spl_frontend_macros" }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
pretty_assertions = "1.3.0"

[[bench]]
name = "benches"
harness = false
